### ISSUE TITLE
Multi scale testing problem

### ISSUE THREAD

**Issue by JiYuanFeng** [PkuRainBow/OCNet.pytorch#38]
Can this project support multi scale testing? thank!

**Comment by PkuRainBow** [comment]
We have provided the parameter TEST_USE_MS  to support multi-scale testing.

**Comment by JiYuanFeng** [comment]
Sorry ! I think I am wrong. actually i am wondering to know is the project support Multi-GPU testing

**Comment by PkuRainBow** [comment]
You can infer that we support multi-gpu if you have checked the eval.py,  We recommend you to spend some effort before you ask for help

**Comment by JiYuanFeng** [comment]
Thank you for your suggestion. 
Actually I have view your code for several times,  and I realize the problem is the fix size in cityscape data set, which mean you can simply use other guys' code and directly use the parallel module  in pytorch.
This implement is not suitable for some unfix data set. On the Whole, Thanks for your contribution.
At last, We also recommend you spend more efforts to respect to the simple or maybe “stupid” problems.
